name: mymovie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 5.0.2
  intl: 0.18.0
  sqflite: 2.0.2
  path_provider: ^2.0.9
  permission_handler: 10.0.0
  flutter_background_service: 2.4.6
  flutter_background_service_android: ^3.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

